routes/web.php
<?php

use App\Models\Project;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth\AuthController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\Master\FileController;
use App\Http\Controllers\Master\AreaController;
use App\Http\Controllers\Arsip\ArsipController;
use App\Http\Controllers\Setting\MenuController;
use App\Http\Controllers\Setting\RoleController;
use App\Http\Controllers\Setting\UserController;
use App\Http\Controllers\Master\VendorController;
use App\Http\Controllers\Finance\ExpendController;
use App\Http\Controllers\Log\LogProjectController;
use App\Http\Controllers\Master\CompanyController;
use App\Http\Controllers\Master\CustomerController;
use App\Http\Controllers\Master\PositionController;
use App\Http\Controllers\Master\EmployeeController;
use App\Http\Controllers\Log\LogActivityController;
use App\Http\Controllers\Project\ProjectController;
use App\Http\Controllers\Setting\LockDataController;
use App\Http\Controllers\Finance\IncentiveController;
use App\Http\Controllers\Setting\PermissionController;
use App\Http\Controllers\Project\ProjectTypeController;
use App\Http\Controllers\Project\ProjectShopController;
use App\Http\Controllers\Report\ReportExpendController;
use App\Http\Controllers\Saldo\EmployeeSaldoController;
use App\Http\Controllers\Report\ReportProjectController;
use App\Http\Controllers\Setting\FormatNumberController;
use App\Http\Controllers\Finance\DebtPaymentPOController;
use App\Http\Controllers\Project\ProjectVendorController;
use App\Http\Controllers\Project\ProjectPaymentController;
use App\Http\Controllers\Finance\CategoryExpendController;
use App\Http\Controllers\Master\FormulaController;
use App\Http\Controllers\Master\MaterialController;
use App\Http\Controllers\Master\UnitController;
use App\Http\Controllers\Report\ReportLossProfitController;
use App\Http\Controllers\Report\ReportProjectExpendController;
use App\Http\Controllers\Project\ProjectImplementationController;
use App\Http\Controllers\Project\SimulationController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::match(['get', 'post'], 'login', [AuthController::class, 'index'])->name('login');
Route::match(['get', 'post'], 'logout', [AuthController::class, 'logout'])->name('logout');

Route::middleware(['auth'])->group(function () {
    Route::get('/', [DashboardController::class, 'index'])->name('dashboard');
    Route::get('change-language/{locale}', [DashboardController::class, 'change_language'])->name('change.language');

    /**
    * Setting
    * */
    Route::name('setting.')->prefix('setting')->group(function () {
        Route::name('role.')->prefix('role')->group(function(){
            Route::resource('', RoleController::class, ['parameters' => [
                '' => 'id',
            ]])->only([
                'index', 'edit', 'create', 'store', 'update', 'destroy'
            ]);

            Route::post('access', [RoleController::class, 'access'])->name('access');
        });

        Route::resource('permission', PermissionController::class)->only([
            'index', 'edit', 'create', 'store', 'update', 'destroy'
        ])->names('permission');

        Route::name('user.')->prefix('user')->group(function(){
            Route::resource('', UserController::class, ['parameters' => [
                '' => 'id',
            ]])->only([
                'index', 'edit', 'create', 'store', 'update', 'destroy', 'show'
            ]);

            Route::get('{id}/change-status/{status}', [UserController::class, 'change_status'])->name('change.status');
        });

        Route::resource('menu', MenuController::class)->only([
            'index', 'edit', 'create', 'store', 'update', 'destroy'
        ])->names('menu');

        Route::resource('lock-data', LockDataController::class)->only([
            'index', 'edit', 'create', 'store', 'update', 'destroy'
        ])->names('lock_data');

        Route::resource('format-number', FormatNumberController::class)->only([
            'index', 'edit', 'create', 'store', 'update', 'destroy'
        ])->names('format_number');
    });

    /**
    * Master
    * */
    Route::name('master.')->prefix('master')->group(function () {
        Route::name('company.')->prefix('company')->group(function () {
            Route::resource('', CompanyController::class, ['parameters' => [
                '' => 'id',
            ]])->only([
                'index', 'edit', 'create', 'store', 'update', 'destroy', 'show'
            ]);
        });
        Route::name('position.')->prefix('position')->group(function () {
            Route::resource('', PositionController::class, ['parameters' => [
                '' => 'id',
            ]])->only([
                'index', 'edit', 'create', 'store', 'update', 'destroy'
            ]);
        });
        Route::name('area.')->prefix('area')->group(function () {
            Route::resource('', AreaController::class, ['parameters' => [
                '' => 'id',
            ]])->only([
                'index', 'edit', 'create', 'store', 'update', 'destroy'
            ]);
        });
        Route::name('unit.')->prefix('unit')->group(function () {
            Route::resource('', UnitController::class, ['parameters' => [
                '' => 'id',
            ]])->only([
                'index', 'edit', 'create', 'store', 'update', 'destroy'
            ]);
        });
        Route::name('employee.')->prefix('employee')->group(function () {
            Route::resource('', EmployeeController::class, ['parameters' => [
                '' => 'employee',
            ]])->only([
                'index', 'edit', 'create', 'store', 'update', 'destroy', 'show'
            ]);

            Route::get('{id}/change-status/{status}', [EmployeeController::class, 'change_status'])->name('change.status');
        });
        Route::name('customer.')->prefix('customer')->group(function () {
            Route::resource('', CustomerController::class, ['parameters' => [
                '' => 'customer',
            ]])->only([
                'index', 'edit', 'create', 'store', 'update', 'destroy', 'show'
            ]);
        });
        Route::name('material.')->prefix('material')->group(function () {
            Route::resource('', MaterialController::class, ['parameters' => [
                '' => 'material',
            ]])->only([
                'index', 'edit', 'create', 'store', 'update', 'destroy', 'show'
            ]);
        });
        Route::name('vendor.')->prefix('vendor')->group(function () {
            Route::resource('', VendorController::class, ['parameters' => [
                '' => 'vendor',
            ]])->only([
                'index', 'edit', 'create', 'store', 'update', 'destroy', 'show'
            ]);
        });
        Route::name('file.')->prefix('file')->group(function () {
            // Route::resource('', FileController::class, ['parameters' => [
            //     '' => 'file',
            // ]])->only([
            //     'index', 'edit', 'create', 'store', 'update', 'destroy', 'show'
            // ]);
        });
        Route::name('formula.')->prefix('formula')->group(function () {
            Route::resource('', FormulaController::class, ['parameters' => [
                '' => 'formula',
            ]])->only([
                'index', 'edit', 'create', 'store', 'update', 'destroy', 'show'
            ]);
        });
    });

    /**
    * Log
    * */
    Route::name('log.')->prefix('log')->group(function () {
        Route::resource('activity', LogActivityController::class)->only([
            'index'
        ])->names('activity');

        Route::get('/project', [LogProjectController::class, 'index'])->name('project.index');
    });

    Route::prefix('arsip')->name('arsip.')->group(function() {
        Route::name('arsip.')->prefix('arsip')->group(function(){
            Route::resource('', ArsipController::class,['parameters' => [
                '' => 'arsip',
            ]])->only([
                'index', 'edit', 'create', 'store', 'update', 'destroy', 'show'
            ]);
        });
    });

    Route::prefix('project')->name('project.')->group(function() {
        Route::name('project.')->prefix('project')->group(function(){
            Route::get('worker/{id}',[ProjectController::class, 'change_worker'])
                ->name('change.worker');
            Route::post('worker/{id}/update',[ProjectController::class, 'change_worker_update'])
                ->name('change.worker.update');

            Route::get('done',[ProjectController::class, 'index'])
                ->defaults('status', Project::STATUS_DONE)
                ->name('index.done');

            Route::get('change/{id}/done',[ProjectController::class, 'change_status'])
                ->defaults('status', Project::STATUS_DONE)
                ->name('change.status.done');
            Route::get('change/{id}/close',[ProjectController::class, 'change_status'])
                ->defaults('status', Project::STATUS_CLOSE)
                ->name('change.status.close');
            Route::get('change/{id}/cancel',[ProjectController::class, 'change_status'])
                ->defaults('status', Project::STATUS_CANCEL)
                ->name('change.status.cancel');

            Route::resource('', ProjectController::class,['parameters' => [
                '' => 'project',
            ]])->only([
                'index', 'edit', 'create', 'store', 'update', 'destroy', 'show'
            ]);
        });

        Route::name('project_vendor.')->prefix('project-vendor')->group(function(){

app/Models/LogActivity.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class LogActivity extends Model
{
    use SoftDeletes;

    const TRANSACTION_CREATE = 1;
    const TRANSACTION_UPDATE = 2;
    const TRANSACTION_DELETE = 3;

    protected $table = 'log_activity';
    protected $fillable = ['log_datetime', 'user_id', 'transaction_type', 'information', 'record_id', 'data_before', 'data_after', 'record_type', 'table', 'data_change'];

    /**
     * Get the user record associated with the user.
     */
    public function user()
    {
        return $this->belongsTo(User::class)->withTrashed();
    }

    /**
     * Get the transaction record associated with the table transaction.
     */
    public function record()
    {
        return $this->morphTo();
    }

    public function getRecordTypeNameAttribute()
    {
        return str_replace(__NAMESPACE__ . '\\', '', $this->record_type);
    }

    /*************
    * SCOPE
    ***************/
    public function scopeTransactionType($query, $type)
    {
        return $query->where('transaction_type', $type);
    }
}

app/Http/Controllers/Log/LogActivityController.php
<?php

namespace App\Http\Controllers\Log;

use App\Util\Base\CoreController;
use App\Models\LogActivity;
use App\Util\Helpers\Util;
use App\Util\Base\Layout;
use App\Models\user;

class LogActivityController extends CoreController
{
    public function index()
    {
        $query = LogActivity::with('user', 'record')->orderBy('id','DESC');

        if( request('search_datetime') )
        {
            $search_datetime = Util::get('search_datetime');
            $search_datetime = explode(" - ", $search_datetime);

            $query->whereBetween('log_datetime', $search_datetime);
        }

        if( request('search_table') )
        {
            $query->where('table', Util::get('search_table'));
        }

        if( request('search_user_id') )
        {
            $query->where('user_id', Util::get('search_user_id'));
        }

        if( request('_ri') )
        {
            $query->where('record_id', Util::get('_ri'));
        }

        if( is_numeric(request('search_transaction_type')) )
        {
            $query->transactionType(Util::get('search_transaction_type'));
        }

        $logs = $query->paginate(request('showing', Layout::ROW_PER_PAGE))->appends( request()->except(["page"]) );
        $tables = LogActivity::select('table')->groupBy('table')->get()->pluck('table')->unique();
        $users = User::active()->get()->pluck('name','id');

        return Layout::render('log.log_activity.index', [
            "logs" => $logs,
            "tables" => $tables,
            "users" => $users,
        ]);
    }
}

app/Http/Controllers/Log/LogProjectController.php
<?php

namespace App\Http\Controllers\Log;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\LogActivity;
use App\Util\Helpers\Util;
use App\Models\Project;

class LogProjectController extends Controller
{
    public function index(Request $request)
    {
        $query = LogActivity::whereIn('record_type', [
            Project::class,
            ProjectDebtPayment::class,
            ProjectImplementation::class,
            ProjectJob::class,
            ProjectPayment::class,
            ProjectShop::class,
            ProjectVendor::class,
            ProjectShopDetail::class,
        ]);

        $date = [
            date('Y-m-d 00:00', strtotime('-7days')),
            date('Y-m-d 23:59'),
        ];

        if (request('_dt')) {
            $date = Util::get('_dt');
            $date = explode(" - ", $date);
        }
        $query->whereBetween('log_datetime', $date);

        $query->selectRaw("log_activity.*, log_datetime::DATE as date");
        $logs = $query->get();

        return view('log.project.index', [
            'logs' => $logs,
            'date' => implode(' - ', $date),
        ]);
    }
}

app/Http/Controllers/Project/ProjectTypeController.php
<?php

namespace App\Http\Controllers\Project;

use App\Http\Requests\Project\ProjectTypeRequest;
use Illuminate\Support\MessageBag;
use App\Util\Base\CoreController;
use App\Models\ProjectType;
use App\Util\Helpers\Util;
use App\Util\Base\Layout;

class ProjectTypeController extends CoreController
{
    public function index()
    {
        $query = ProjectType::query();

        if (request('_k')) {
            $query->where(function($q) {
                $q->whereLike('name', Util::get('_k'));
            });
        }

        $projectTypes = $query->sortable()->paginate(request('showing', Layout::ROW_PER_PAGE))->appends(request()->except(["page"]));

        return Layout::render('project.project_type.index', [
            "projectTypes" => $projectTypes,
        ]);
    }

    public function edit($id)
    {
        $projectType = ProjectType::find($id);
        $projectType = $projectType ? $projectType->toArray() : [];

        return response()->json([
            'url_edit' => route('project.project_type.update', $id),
            'data' => $projectType
        ]);
    }

    public function store(ProjectTypeRequest $request)
    {
        return $this->store_update($request, new ProjectType());
    }

    public function update(ProjectTypeRequest $request, ProjectType $projectType)
    {
        return $this->store_update($request, $projectType);
    }

    private function store_update(ProjectTypeRequest $request, ProjectType $projectType)
    {
        $redirect = redirect()->route('project.project_type.index');
        $result = [
            'status' => true,
            'error' => new MessageBag
        ];

        \DB::beginTransaction();
        $input = $request->only([
            'name',
            'description',
            'price',
        ]);

        try {
            $model = $projectType;
            $model->fill($input);
            $model->save();
            \DB::commit();

            $redirect->with('success', trans('global.success_save'));
        } catch (Exception $e) {
            \DB::rollback();

            if (!empty($e->getMessage())) {
                $result['error']->add('throw', $e->getMessage());
            }

            $redirect->withInput( $request->except(['token']) )
                        ->withErrors($result['error'])
                        ->with('error', sprintf('%s', trans("global.failed_save")) );
        }

        return $redirect;
    }

    public function destroy(ProjectType $projectType)
    {
        \DB::beginTransaction();
        $name = $projectType->name;

        $result = $this->delete($projectType, 'soft');
        if($result["status"]){
            session()->flash('success', sprintf("%s %s : %s", trans("global.success_delete"), trans("project_type.title"), $name));
            \DB::commit();
        }else{
            session()->flash('error', sprintf("%s %s : %s", trans("global.failed_delete"), trans("project_type.title"), $name));
            \DB::rollback();
        }

        return response()->json(["status" => $result["status"]]);
    }

    public function ajaxProjectType()
    {
        $params = request()->all();

        $query = ProjectType::query();

        $q = array_key_exists('query', $params) ? $params['query'] : (array_key_exists('q', $params) ? $params['q'] : '');
        if ($q) {
            $query->whereLike("name", $q)
                    ->orWhereLike('price', $q);
        }

        $query->limit(20);

        $list = [];
        foreach ($query->get() as $projectType) {
            $list[] = [
                'id' => $projectType->id,
                'text' => sprintf('%s - %s', $projectType->name, Util::format_currency($projectType->price)),
            ];
        }

        return response()->json([
            "items" => $list,
            "count" => count($list)
        ]);
    }
}

resources/views/log/project/index.blade.php
@extends('layouts.admin')

@section('content')
<div class="row">
    <div class="col-lg-12">
        <!--begin::List Widget 9-->
        <div class="card card-custom gutter-b">
            <!--begin::Header-->
            <div class="card-header align-items-center border-0 mt-4">
                <h3 class="card-title align-items-start flex-column">
                    <span class="font-weight-bolder text-dark">@lang('log_activity.title') @lang('project.title')</span>
                    <span class="text-muted mt-3 font-weight-bold font-size-sm">@lang('global.list')</span>
                </h3>
            </div>
            <!--end::Header-->
            <!--begin::Body-->
            <div class="card-body pt-4">
                <!--begin::Search Form-->
                <div class="mb-7">
                    <form id="form-search-log" role="form" action="{{ route(request()->route()->getName()) }}">
                        <div class="row align-items-center">
                            <div class="col-lg-12">
                                <div class="row align-items-center">
                                    <div class="col-md-4 my-2 my-md-0">
                                        <div class="input-icon">
                                            <input type="text" class="form-control datetime-rangepicker" placeholder="@lang('log_activity.label.date')" name="_dt" value="{{ request('_dt', $date) }}" autocomplete="off" id="search_date" />
                                            <span>
                                                <i class="flaticon2-search-1 text-muted"></i>
                                            </span>
                                        </div>
                                    </div>
                                    <div class="col-md-4 my-2 my-md-0">
                                        <div class="d-flex align-items-center">
                                            <label class="mr-3 mb-0 d-none d-md-block">@lang('log_activity.label.record_type'):</label>
                                            <select class="form-control" id="search_record_type" name="_rt">
                                                <option value="">@lang('global.all')</option>
                                                @foreach (trans('log_activity.list.transaction_type') as $id => $name)
                                                <option value="{{ $id }}" {{ is_numeric(request('_rt')) && $id == request('_rt') ? 'selected' : '' }}>{{ $name }}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
                <!--end::Search Form-->

                @php
                    $color_type = ["success", "info", "danger"];
                @endphp
                @foreach ($logs->groupBy('date') as $date => $log_days)
                <h3 class="card-title align-items-start flex-column mt-10 mb-5 p-5 bg-light-secondary">
                    <span class="font-weight-bolder text-dark">{{ date('d M Y', strtotime($date)) }}</span>
                </h3>
                <div class="timeline timeline-5 mt-3">
                    @foreach ($log_days->sortBy('log_datetime') as $log)
                        <!--begin::Item-->
                        <div class="timeline-item align-items-start">
                            <!--begin::Label-->
                            <div class="timeline-label font-weight-bolder text-dark-75 font-size-lg">
                                {{ date('H:i', strtotime($log->log_datetime)) }}
                            </div>
                            <!--end::Label-->
                            <!--begin::Badge-->
                            <div class="timeline-badge">
                                <i class="fa fa-genderless text-{{ $color_type[$log->transaction_type] }} icon-xl"></i>
                            </div>
                            <!--end::Badge-->
                            <!--begin::Text-->
                            <div class="font-weight-mormal font-size-lg timeline-content pl-3">
                                {{ $log->user->name }} <span class="label label-inline label-light-{{ $color_type[$log->transaction_type] }} font-weight-bold">@lang("log_activity.list.transaction_type.$log->transaction_type")</span>
                                <span class="text-muted">
                                    {{ $log->record_type_name }}
                                </span>
                                <span class="font-weight-bolder text-dark-75 font-size-sm">
                                    {{ $log->record->no_project }}
                                </span>
                            </div>
                            <!--end::Text-->
                        </div>
                        <!--end::Item-->
                    @endforeach
                </div>
                <!--end: Items-->
                @endforeach
            </div>
            <!--end: Card Body-->
        </div>
        <!--end: Card-->
        <!--end: List Widget 9-->
    </div>
</div>
@endsection

@push('js')
<script>
    $('#search_record_type').change(function() {
        $('#form-search-log').submit();
    });
    $('#search_date').change(function() {
        console.log('masuk');
        $('#form-search-log').submit();
    });
</script>
@endpush