routes/web.php
<?php

use App\Models\Project;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth\AuthController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\Master\FileController;
use App\Http\Controllers\Master\AreaController;
use App\Http\Controllers\Arsip\ArsipController;
use App\Http\Controllers\Setting\MenuController;
use App\Http\Controllers\Setting\RoleController;
use App\Http\Controllers\Setting\UserController;
use App\Http\Controllers\Master\VendorController;
use App\Http\Controllers\Finance\ExpendController;
use App\Http\Controllers\Log\LogProjectController;
use App\Http\Controllers\Master\CompanyController;
use App\Http\Controllers\Master\CustomerController;
use App\Http\Controllers\Master\PositionController;
use App\Http\Controllers\Master\EmployeeController;
use App\Http\Controllers\Log\LogActivityController;
use App\Http\Controllers\Project\ProjectController;
use App\Http\Controllers\Setting\LockDataController;
use App\Http\Controllers\Finance\IncentiveController;
use App\Http\Controllers\Setting\PermissionController;
use App\Http\Controllers\Project\ProjectTypeController;
use App\Http\Controllers\Project\ProjectShopController;
use App\Http\Controllers\Report\ReportExpendController;
use App\Http\Controllers\Saldo\EmployeeSaldoController;
use App\Http\Controllers\Report\ReportProjectController;
use App\Http\Controllers\Setting\FormatNumberController;
use App\Http\Controllers\Finance\DebtPaymentPOController;
use App\Http\Controllers\Project\ProjectVendorController;
use App\Http\Controllers\Project\ProjectPaymentController;
use App\Http\Controllers\Finance\CategoryExpendController;
use App\Http\Controllers\Master\FormulaController;
use App\Http\Controllers\Master\MaterialController;
use App\Http\Controllers\Master\UnitController;
use App\Http\Controllers\Report\ReportLossProfitController;
use App\Http\Controllers\Report\ReportProjectExpendController;
use App\Http\Controllers\Project\ProjectImplementationController;
use App\Http\Controllers\Project\SimulationController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::match(['get', 'post'], 'login', [AuthController::class, 'index'])->name('login');
Route::match(['get', 'post'], 'logout', [AuthController::class, 'logout'])->name('logout');

Route::middleware(['auth'])->group(function () {
    Route::get('/', [DashboardController::class, 'index'])->name('dashboard');
    Route::get('change-language/{locale}', [DashboardController::class, 'change_language'])->name('change.language');

    /**
    * Setting
    * */
    Route::name('setting.')->prefix('setting')->group(function () {
        Route::name('role.')->prefix('role')->group(function(){
            Route::resource('', RoleController::class, ['parameters' => [
                '' => 'id',
            ]])->only([
                'index', 'edit', 'create', 'store', 'update', 'destroy'
            ]);

            Route::post('access', [RoleController::class, 'access'])->name('access');
        });

        Route::resource('permission', PermissionController::class)->only([
            'index', 'edit', 'create', 'store', 'update', 'destroy'
        ])->names('permission');

        Route::name('user.')->prefix('user')->group(function(){
            Route::resource('', UserController::class, ['parameters' => [
                '' => 'id',
            ]])->only([
                'index', 'edit', 'create', 'store', 'update', 'destroy', 'show'
            ]);

            Route::get('{id}/change-status/{status}', [UserController::class, 'change_status'])->name('change.status');
        });

        Route::resource('menu', MenuController::class)->only([
            'index', 'edit', 'create', 'store', 'update', 'destroy'
        ])->names('menu');

        Route::resource('lock-data', LockDataController::class)->only([
            'index', 'edit', 'create', 'store', 'update', 'destroy'
        ])->names('lock_data');

        Route::resource('format-number', FormatNumberController::class)->only([
            'index', 'edit', 'create', 'store', 'update', 'destroy'
        ])->names('format_number');
    });

    /**
    * Master
    * */
    Route::name('master.')->prefix('master')->group(function () {
        Route::name('company.')->prefix('company')->group(function () {
            Route::resource('', CompanyController::class, ['parameters' => [
                '' => 'id',
            ]])->only([
                'index', 'edit', 'create', 'store', 'update', 'destroy', 'show'
            ]);
        });
        Route::name('position.')->prefix('position')->group(function () {
            Route::resource('', PositionController::class, ['parameters' => [
                '' => 'id',
            ]])->only([
                'index', 'edit', 'create', 'store', 'update', 'destroy'
            ]);
        });
        Route::name('area.')->prefix('area')->group(function () {
            Route::resource('', AreaController::class, ['parameters' => [
                '' => 'id',
            ]])->only([
                'index', 'edit', 'create', 'store', 'update', 'destroy'
            ]);
        });
        Route::name('unit.')->prefix('unit')->group(function () {
            Route::resource('', UnitController::class, ['parameters' => [
                '' => 'id',
            ]])->only([
                'index', 'edit', 'create', 'store', 'update', 'destroy'
            ]);
        });
        Route::name('employee.')->prefix('employee')->group(function () {
            Route::resource('', EmployeeController::class, ['parameters' => [
                '' => 'employee',
            ]])->only([
                'index', 'edit', 'create', 'store', 'update', 'destroy', 'show'
            ]);

            Route::get('{id}/change-status/{status}', [EmployeeController::class, 'change_status'])->name('change.status');
        });
        Route::name('customer.')->prefix('customer')->group(function () {
            Route::resource('', CustomerController::class, ['parameters' => [
                '' => 'customer',
            ]])->only([
                'index', 'edit', 'create', 'store', 'update', 'destroy', 'show'
            ]);
        });
        Route::name('material.')->prefix('material')->group(function () {
            Route::resource('', MaterialController::class, ['parameters' => [
                '' => 'material',
            ]])->only([
                'index', 'edit', 'create', 'store', 'update', 'destroy', 'show'
            ]);
        });
        Route::name('vendor.')->prefix('vendor')->group(function () {
            Route::resource('', VendorController::class, ['parameters' => [
                '' => 'vendor',
            ]])->only([
                'index', 'edit', 'create', 'store', 'update', 'destroy', 'show'
            ]);
        });
        Route::name('file.')->prefix('file')->group(function () {
            // Route::resource('', FileController::class, ['parameters' => [
            //     '' => 'file',
            // ]])->only([
            //     'index', 'edit', 'create', 'store', 'update', 'destroy', 'show'
            // ]);
        });
        Route::name('formula.')->prefix('formula')->group(function () {
            Route::resource('', FormulaController::class, ['parameters' => [
                '' => 'formula',
            ]])->only([
                'index', 'edit', 'create', 'store', 'update', 'destroy', 'show'
            ]);
        });
    });

    /**
    * Log
    * */
    Route::name('log.')->prefix('log')->group(function () {
        Route::resource('activity', LogActivityController::class)->only([
            'index'
        ])->names('activity');

        Route::get('/project', [LogProjectController::class, 'index'])->name('project.index');
    });

    Route::prefix('arsip')->name('arsip.')->group(function() {
        Route::name('arsip.')->prefix('arsip')->group(function(){
            Route::resource('', ArsipController::class,['parameters' => [
                '' => 'arsip',
            ]])->only([
                'index', 'edit', 'create', 'store', 'update', 'destroy', 'show'
            ]);
        });
    });

    Route::prefix('project')->name('project.')->group(function() {
        Route::name('project.')->prefix('project')->group(function(){
            Route::get('worker/{id}',[ProjectController::class, 'change_worker'])
                ->name('change.worker');
            Route::post('worker/{id}/update',[ProjectController::class, 'change_worker_update'])
                ->name('change.worker.update');

            Route::get('done',[ProjectController::class, 'index'])
                ->defaults('status', Project::STATUS_DONE)
                ->name('index.done');

            Route::get('change/{id}/done',[ProjectController::class, 'change_status'])
                ->defaults('status', Project::STATUS_DONE)
                ->name('change.status.done');
            Route::get('change/{id}/close',[ProjectController::class, 'change_status'])
                ->defaults('status', Project::STATUS_CLOSE)
                ->name('change.status.close');
            Route::get('change/{id}/cancel',[ProjectController::class, 'change_status'])
                ->defaults('status', Project::STATUS_CANCEL)
                ->name('change.status.cancel');

            Route::resource('', ProjectController::class,['parameters' => [
                '' => 'project',
            ]])->only([
                'index', 'edit', 'create', 'store', 'update', 'destroy', 'show'
            ]);
        });

        Route::name('project_vendor.')->prefix('project-vendor')->group(function(){

app/Models/LogActivity.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class LogActivity extends Model
{
    use SoftDeletes;

    const TRANSACTION_CREATE = 1;
    const TRANSACTION_UPDATE = 2;
    const TRANSACTION_DELETE = 3;

    protected $table = 'log_activity';
    protected $fillable = ['log_datetime', 'user_id', 'transaction_type', 'information', 'record_id', 'data_before', 'data_after', 'record_type', 'table', 'data_change'];

    /**
     * Get the user record associated with the user.
     */
    public function user()
    {
        return $this->belongsTo(User::class)->withTrashed();
    }

    /**
     * Get the transaction record associated with the table transaction.
     */
    public function record()
    {
        return $this->morphTo();
    }

    public function getRecordTypeNameAttribute()
    {
        return str_replace(__NAMESPACE__ . '\\', '', $this->record_type);
    }

    /*************
    * SCOPE
    ***************/
    public function scopeTransactionType($query, $type)
    {
        return $query->where('transaction_type', $type);
    }
}

app/Http/Controllers/Log/LogActivityController.php
<?php

namespace App\Http\Controllers\Log;

use App\Util\Base\CoreController;
use App\Models\LogActivity;
use App\Util\Helpers\Util;
use App\Util\Base\Layout;
use App\Models\user;

class LogActivityController extends CoreController
{
    public function index()
    {
        $query = LogActivity::with('user', 'record')->orderBy('id','DESC');

        if( request('search_datetime') )
        {
            $search_datetime = Util::get('search_datetime');
            $search_datetime = explode(" - ", $search_datetime);

            $query->whereBetween('log_datetime', $search_datetime);
        }

        if( request('search_table') )
        {
            $query->where('table', Util::get('search_table'));
        }

        if( request('search_user_id') )
        {
            $query->where('user_id', Util::get('search_user_id'));
        }

        if( request('_ri') )
        {
            $query->where('record_id', Util::get('_ri'));
        }

        if( is_numeric(request('search_transaction_type')) )
        {
            $query->transactionType(Util::get('search_transaction_type'));
        }

        $logs = $query->paginate(request('showing', Layout::ROW_PER_PAGE))->appends( request()->except(["page"]) );
        $tables = LogActivity::select('table')->groupBy('table')->get()->pluck('table')->unique();
        $users = User::active()->get()->pluck('name','id');

        return Layout::render('log.log_activity.index', [
            "logs" => $logs,
            "tables" => $tables,
            "users" => $users,
        ]);
    }
}

app/Http/Controllers/Log/LogProjectController.php
<?php

namespace App\Http\Controllers\Log;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\LogActivity;
use App\Util\Helpers\Util;
use App\Models\Project;

class LogProjectController extends Controller
{
    public function index(Request $request)
    {
        $query = LogActivity::whereIn('record_type', [
            Project::class,
            ProjectDebtPayment::class,
            ProjectImplementation::class,
            ProjectJob::class,
            ProjectPayment::class,
            ProjectShop::class,
            ProjectVendor::class,
            ProjectShopDetail::class,
        ]);

        $date = [
            date('Y-m-d 00:00', strtotime('-7days')),
            date('Y-m-d 23:59'),
        ];

        if (request('_dt')) {
            $date = Util::get('_dt');
            $date = explode(" - ", $date);
        }
        $query->whereBetween('log_datetime', $date);

        $query->selectRaw("log_activity.*, log_datetime::DATE as date");
        $logs = $query->get();

        return view('log.project.index', [
            'logs' => $logs,
            'date' => implode(' - ', $date),
        ]);
    }
}

resources/views/log/log_activity/index.blade.php
@extends('layouts.admin')

@inject('util', 'App\Util\Helpers\Util')

@section('content')
<div class="row">
    <div class="col-lg-12">
        <div class="card card-secondary">
            <div class="card-header">
                <h3 class="card-title">@lang('global.search') @lang('log_activity.title')</h3>
            </div>
            <!-- /.card-header -->
            @include( $template . 'log.log_activity.search')
        </div>
    </div>
</div>
<div class="row" id="content-log_activity">
    <div class="col-xs-12 col-sm-12 col-lg-12">
        <div class="card card-primary card-outline">
            <div class="card-header">
                <h3 class="card-title"> @lang('global.list') @lang('log_activity.title')</h3>
            </div>
            <div class="card-body table-responsive p-0">
                <table class="table table-stripped table-hover">
                    <thead>
                        <tr>
                            <th class="text-center">@lang('global.no')</th>
                            <th>@lang('log_activity.label.log_datetime')</th>
                            <th>@lang('log_activity.label.transaction_type')</th>
                            <th>@lang('log_activity.label.table')</th>
                            <th>@lang('global.action')</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if( isset($logs) && count($logs) > 0 )
                        @foreach( $logs as $i => $r)
                        <tr>
                            <td class="text-center">{{ $logs->firstItem() + $i }}</td>
                            <td class="text-wrap">
                                {{ $r->user->name }}
                                <p class="m-0">
                                    <small>
                                        <strong>@lang('log_activity.label.information'):</strong> {{ $util->formatDate($r->log_datetime, $util->FORMAT_DATETIME_ID_LONG_DAY) }}
                                    </small>
                                </p>
                            </td>
                            <td class="text-wrap">
                                <h6 class="mb-1">
                                    @lang('log_activity.list.transaction_type.'.$r->transaction_type)
                                </h6>
                                <p class="m-0">
                                    <small>
                                        <strong>@lang('log_activity.label.information'):</strong> {{ $r->information }}
                                    </small>
                                </p>
                                <p class="m-0">
                                    <small>
                                        <strong>@lang('log_activity.label.record_id'):</strong> {{ $r->record ? $r->record->defaultName() : $r->record_id }}
                                    </small>
                                </p>
                            </td>
                            <td class="">
                                <h6 class="mb-1">
                                    {{ $r->table }}
                                </h6>
                                <p class="m-0">
                                    <small>
                                        <strong>@lang('log_activity.label.record_type'):</strong> {{ $r->record_type }}
                                    </small>
                                </p>
                            </td>
                            <td class="text-wrap">
                                <a title="@lang('global.edit')"class="btn btn-sm btn-info" data-toggle="collapse" href="#detail-{{$i}}" class="accordion-toggle">
                                    <i class="fas fa-eye m-0"></i>
                                </a>
                            </td>
                        </tr>
                        <tr>
                            <td colspan="5" class="hiddenRow">
                                <div id="detail-{{$i}}" class="accordian-body collapse">
                                    <table class="table table-stripped table-hover">
                                        <thead>
                                            <th>@lang('global.column')</th>
                                            <th>@lang('log_activity.label.data_before')</th>
                                            <th>@lang('log_activity.label.data_change')</th>
                                        </thead>
                                        <tbody>
                                            @php
                                                $data_before = json_decode($r->data_before, TRUE);
                                                if(strtotime($r->log_datetime) < strtotime('2020-05-18')){
                                                    $data_before = json_decode($r->data_after, TRUE);
                                                }
                                            @endphp
                                            @foreach (json_decode($r->data_change, TRUE) as $col => $value)
                                                <tr>
                                                    <td>{{ $col }}</td>
                                                    <td>
                                                        @if (array_key_exists($col, $data_before))
                                                            {!! $data_before[$col] !!}
                                                        @else
                                                            -
                                                        @endif
                                                    </td>
                                                    <td>{!! $value !!}</td>
                                                </tr>
                                            @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            </td>
                        </tr>
                        @endforeach
                        @else
                        <tr>
                            <td colspan="5" class="text-center">@lang('global.data_not_available')</td>
                        </tr>
                        @endif
                    </tbody>
                </table>
            </div>
            @if( isset($logs) && count($logs) > 0 )
            {!! \App\Util\Base\Layout::paging($logs) !!}
            @endif
        </div>
    </div>
</div>
@stop

@push('css')
    <style>
        .hiddenRow {
            padding: 0 50px !important;
        }
    </style>
@endpush
@push('js')
    {{-- <script type="text/javascript" src="{{ asset('js/admin/finance/log_activity.js') }}?{{ config('app.version') }}"></script> --}}
@endpush

resources/views/log/log_activity/search.blade.php
<!-- form start -->
<form role="form" action="{{ route('log.activity.index') }}">
    <div class="card-body">
        <div class="row">
            <div class="col-4">
                <div class="form-group">
                    <label for="_ri">@lang('log_activity.label.record_id')</label>
                    <input type="text" name="_ri" class="form-control" value="{{ request('_ri') }}">
                </div>
            </div>
            <div class="col-4">
                <div class="form-group">
                    <label for="search_datetime">@lang('log_activity.label.log_datetime')</label>
                    <input type="text" name="search_datetime" class="form-control date-rangepicker" value="{{ request('search_datetime') }}">
                </div>
            </div>
            <div class="col-4">
                <div class="form-group">
                    <label for="search_table">@lang('log_activity.label.table')</label>
                    <select name="search_table"  class="form-control select2" data-placeholder="Select" style="width: 100%;">
                        <option value=""></option>
                        @foreach ($tables as $name)
                        <option value="{{ $name }}" {{ request('search_table') == $name ? "selected"  : ""}}>{{ $name }}</option>
                        @endforeach
                    </select>
                </div>
            </div>
            <div class="col-4">
                <div class="form-group">
                    <label for="search_transaction_type">@lang('log_activity.label.transaction_type')</label>
                    <select name="search_transaction_type"  class="form-control select2" data-placeholder="Select" style="width: 100%;">
                        <option value=""></option>
                        @foreach (trans('log_activity.list.transaction_type') as $id => $name)
                        <option value="{{ $id }}" {{ request('search_transaction_type') == $id ? "selected"  : ""}}>{{ $name }}</option>
                        @endforeach
                    </select>
                </div>
            </div>
            <div class="col-4">
                <div class="form-group">
                    <label for="search_user_id">@lang('log_activity.label.user_id')</label>
                    <select name="search_user_id"  class="form-control select2" data-placeholder="Select" style="width: 100%;">
                        <option value=""></option>
                        @foreach ($users as $id => $name)
                        <option value="{{ $id }}" {{ request('search_user_id') == $id ? "selected"  : ""}}>{{ $name }}</option>
                        @endforeach
                    </select>
                </div>
            </div>
        </div>
    </div>
    <!-- /.card-body -->

    <div class="card-footer">
        <a href="{{ route('log.activity.index') }}" class="btn btn-info btn-loader">@lang('global.show_all')</a>
        <button type="submit" class="btn btn-success btn-loader">
            @lang('global.search')
        </button>
    </div>
</form>